name: Build eBPF
on:

  # Trigger this workflow only when ebpf modules changes.
  push:
    paths:
      - 'ebpf_prog/*'
      - '.github/workflows/ebpf.yml'
  pull_request:
    paths:
      - 'ebpf_prog/*'
      - '.github/workflows/ebpf.yml'

  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    name: Build eBPF object
    runs-on: ubuntu-latest
    steps:

    - name: Check out git code
      uses: actions/checkout@v2

    - name: Get and prepare dependencies
      run: |
        set -e
        set -x
        sudo apt install eatmydata
        sudo eatmydata apt install wget tar patch clang llvm libelf-dev libzip-dev flex bison libssl-dev bc rsync python3 binutils linux-headers-generic

    - name: Build eBPF module
      run: |
        set -e
        set -x
        cd ebpf_prog
        for d in /usr/src/linux-headers-*/include/ \
           /usr/src/linux-headers-*/arch/x86/include \
           /usr/src/linux-headers-*/arch/x86/include/generated; do \
            CFLAGS="$CFLAGS -I$d";
        done
        eatmydata clang $CFLAGS -o opensnitch.o opensnitch.c
        eatmydata objdump -h opensnitch.o
        eatmydata llvm-strip -g opensnitch.o
